apiVersion: v1
kind: Pod
metadata:
  name: shipping-web
spec:
  containers:
  - name: nginx
    image: nginx:1.19.1
  initContainers:
  - name: busybox
    image: busybox
    command: ['sh', '-c', 'until nslookup shipping-svc; do echo waiting for the service; sleep 5; done']
